# Generated by Django 4.2.1 on 2023-06-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_strava_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='strava_athlete_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
