# Generated by Django 4.2.1 on 2023-06-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_strava_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='strava_activities_imported',
            field=models.BooleanField(default=False),
        ),
    ]
