# Generated by Django 4.2.1 on 2023-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
