# Generated by Django 4.2.1 on 2023-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_lat_exercise_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='average_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
