# Generated by Django 4.2.1 on 2023-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exercise_average_heartrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='total_elevation_gain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
