# Generated by Django 4.2.1 on 2023-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_total_elevation_gain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lng',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Long', 'Long'), ('Workout', 'Workout'), ('Race', 'Race')], max_length=8),
        ),
    ]
