# Generated by Django 4.2.1 on 2023-06-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_exercise_lat_remove_exercise_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('polyline', models.TextField()),
                ('resource_state', models.IntegerField()),
                ('summary_polyline', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='strava_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='api.map'),
        ),
    ]
