# Generated by Django 4.2.1 on 2023-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_map_exercise_strava_id_exercise_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='max_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='act_type',
            field=models.CharField(choices=[('Run', 'Run'), ('Bike', 'Bike'), ('Swim', 'Swim'), ('Elliptical', 'Elliptical'), ('Walk', 'Walk'), ('Cross Country Ski', 'Cross Country Ski'), ('Alpine Ski', 'Alpine Ski')], default='Run', max_length=30),
        ),
    ]
