# Generated by Django 4.2.1 on 2023-06-04 13:38

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_exercise_calories_alter_exercise_average_heartrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True),
        ),
    ]
