# Generated by Django 4.2.1 on 2023-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_exercise_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-datetime_started']},
        ),
        migrations.AlterField(
            model_name='map',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='resource_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='summary_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
