# Generated by Django 4.2.1 on 2023-06-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_exercise_strava_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='exercise',
        ),
    ]
