# Generated by Django 4.2.1 on 2023-06-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_map_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.map'),
        ),
    ]
