# Generated by Django 4.2.1 on 2023-06-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_exercise_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='exercise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.map'),
        ),
    ]
