# Generated by Django 4.2.1 on 2023-06-21 14:27

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_map_exercise_alter_exercise_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_datetime', datetimeutc.fields.DateTimeUTCField()),
                ('week_end_datetime', datetimeutc.fields.DateTimeUTCField()),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('average_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
