# Generated by Django 4.2.1 on 2023-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_weeklysummarystatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysummarystatistics',
            name='average_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysummarystatistics',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weeklysummarystatistics',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weeklysummarystatistics',
            name='total_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
