# Generated by Django 4.2.1 on 2023-06-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_weeklysummarystatistics_average_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weekly_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.weeklysummarystatistics'),
        ),
    ]
