# Generated by Django 4.2.1 on 2023-06-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_exercise_weekly_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='weekly_summary',
        ),
        migrations.DeleteModel(
            name='WeeklySummaryStatistics',
        ),
    ]
